import { useEffect, useState } from "react";
import { ExternalLink } from "lucide-react";
import { portfolio } from "../data/portfolio";
const GAME_DURATION=20,HITS_TO_WIN=12,TARGET_SIZE=58;
function makeTarget(){return{x:8+Math.random()*84,y:10+Math.random()*78,size:TARGET_SIZE*(.78+Math.random()*.4)}}
export default function GameSection({t}){
 const[running,setRunning]=useState(false),[time,setTime]=useState(GAME_DURATION),[score,setScore]=useState(0),[target,setTarget]=useState(makeTarget),[won,setWon]=useState(false),[lost,setLost]=useState(false);
 useEffect(()=>{if(!running||won||lost)return;const timer=window.setInterval(()=>setTime(current=>{if(current<=1){window.clearInterval(timer);setRunning(false);setLost(true);return 0}return current-1}),1000);return()=>window.clearInterval(timer)},[running,won,lost]);
 const start=()=>{setRunning(true);setTime(GAME_DURATION);setScore(0);setTarget(makeTarget());setWon(false);setLost(false)};
 const hit=()=>{if(!running)return;setScore(current=>{const next=current+1;if(next>=HITS_TO_WIN){setRunning(false);setWon(true)}return next});setTarget(makeTarget())};
 return <section className="game-section" id="game"><div className="section-heading-v5"><div><h2>{t.game.titleA} <em>{t.game.titleB}</em></h2></div><p>{t.game.intro}</p></div><div className="game-panel"><div className="game-topbar"><div><span>{t.game.time}</span><strong>{time}s</strong></div><div><span>{t.game.score}</span><strong>{String(score).padStart(2,"0")} / {HITS_TO_WIN}</strong></div><button onClick={start}>{running?t.game.restart:t.game.start}</button></div><div className="game-arena"><div className="game-grid"/>{running&&<button className="packet" onClick={hit} aria-label="Catch packet" style={{left:`${target.x}%`,top:`${target.y}%`,width:target.size,height:target.size}}>+</button>}{!running&&!won&&!lost&&<div className="game-state"><strong>{t.game.ready}</strong><span>{t.game.readyText}</span><button onClick={start}>{t.game.startRun}</button></div>}{lost&&<div className="game-state"><strong>{t.game.timeout}</strong><span>{score} {t.game.secured}</span><button onClick={start}>{t.game.runAgain}</button></div>}{won&&<div className="game-state is-success"><strong>{t.game.granted}</strong><span>{t.game.ticketUnlocked}</span></div>}</div>{won&&<div className="meeting-ticket"><span>{t.game.ticket}</span><h3>{t.game.congratulations}</h3><p>{t.game.ticketText}</p><div><a href={`mailto:${portfolio.email}`}>Email <ExternalLink size={14}/></a><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={14}/></a><a href={portfolio.github} target="_blank" rel="noreferrer">GitHub <ExternalLink size={14}/></a></div></div>}</div></section>
}