import{useEffect,useState}from"react";import{ArrowDownRight,ArrowUpRight,ExternalLink,Github,Mail,Menu,X}from"lucide-react";

const projects=[
{number:"01",title:"GreenPoint",kicker:"Offline-first field research",description:"A production mobile application for forest scientists to gather forestry data in remote environments without cellular or Wi-Fi connectivity.",stack:["JavaScript","Node.js","Express","Docker","Jenkins"],featured:true,details:["Technical Lead for a 3-person university capstone team.","Designed the layered architecture and core application foundation.","Engineered offline-first mapping, GPS geotagging, and automatic synchronization.","Built the CI/CD pipeline with Jenkins and Docker."],url:"https://github.com/S3eedkabak/GreenPoint-TreeD",accent:"FIELD / SYSTEM"},
{number:"02",title:"MARP Guide RAG",kicker:"Event-driven AI infrastructure",description:"A collaborative RAG chatbot project built around asynchronous processing, retrieval, and conversational AI.",stack:["Java","React","RabbitMQ","RAG","Docker"],details:["Designed asynchronous message flow around RabbitMQ.","Integrated retrieval-augmented generation into the chat workflow.","Worked with a team on a containerized application architecture."],url:"https://github.com/DominykasPivo/MARP-Guide-RAG-Chatbot",accent:"ASYNC / AI"},
{number:"03",title:"Algorithm Lab",kicker:"Data structures in motion",description:"Interactive demonstrations exploring data structures, graph traversal, and runtime behavior across different dataset scales.",stack:["Java","Python","Algorithms"],details:["Built demonstrations for core data structures.","Visualized BFS and DFS graph traversal.","Compared runtime behavior as dataset scale changes."],url:"https://github.com/S3eedkabak",accent:"LOGIC / SCALE"}];

const skills=[
["01","Languages","Java · Python · JavaScript · HTML/CSS · SQL"],
["02","Backend","Node.js · Express · REST APIs · RabbitMQ"],
["03","Architecture","Layered systems · Event-driven architecture · Sync/async workflows"],
["04","AI & Data","RAG pipelines · Vector search · Embeddings · Algorithms"],
["05","DevOps","Docker · Docker Compose · Jenkins · Git · Linux/Unix"]];

function MacBook(){return <div className="mac-stage"><div className="macbook"><div className="lid"><div className="screen"><div className="screen-top"><span>SAEID.KABAK</span><span>SYSTEM / 01</span></div><div className="screen-code"><i/><i/><i/><b>ARCHITECTURE</b><b>APPLICATIONS</b><b>AI SYSTEMS</b></div><div className="screen-cursor"/></div></div><div className="base"><div className="keyboard">{Array.from({length:48},(_,i)=><span key={i}/>)}</div><div className="trackpad"/></div></div><div className="mac-shadow"/></div>}

function ProjectVisual({project}){return <div className="project-visual" aria-hidden="true"><div className="visual-grid"/><div className="visual-orbit orbit-a"/><div className="visual-orbit orbit-b"/><div className="visual-node node-a"/><div className="visual-node node-b"/><div className="visual-node node-c"/><span>{project.accent}</span></div>}

export default function App(){
const[menuOpen,setMenuOpen]=useState(false);
useEffect(()=>{const onScroll=()=>{const section=document.getElementById("system");if(!section)return;const rect=section.getBoundingClientRect();const progress=Math.max(0,Math.min(1,(window.innerHeight-rect.top)/(rect.height+window.innerHeight*.35)));document.documentElement.style.setProperty("--machine-progress",progress.toFixed(3))};onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenuOpen(false)};
return <div className="site">
<header className="nav"><button className="brand" onClick={()=>go("top")}>SK<span>.</span></button><nav className={menuOpen?"nav-links open":"nav-links"}><button onClick={()=>go("work")}>Work</button><button onClick={()=>go("system")}>System</button><button onClick={()=>go("about")}>About</button><button onClick={()=>go("contact")}>Contact</button></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button></header>
<main id="top">
<section className="hero section"><div className="hero-meta"><span>SOFTWARE ENGINEER</span><span>LEIPZIG · GERMANY</span></div><div className="hero-title"><p className="eyebrow">Software, without the theatre.</p><h1>Saeid<br/><em>Kabak</em></h1><div className="hero-line"><span>APPLICATIONS</span><i/><span>DISTRIBUTED SYSTEMS</span><i/><span>AI INFRASTRUCTURE</span></div></div><div className="hero-bottom"><p className="hero-copy">I build the machinery behind useful software: robust applications, asynchronous systems, and AI workflows that have to survive contact with reality.</p><button className="circle-link" onClick={()=>go("work")}><ArrowDownRight/></button></div><div className="hero-mark">ENGINEER / 26</div></section>

<section id="work" className="section work"><div className="section-heading"><span className="section-index">01</span><div><p className="eyebrow">Selected work</p><h2>Things I've<br/><em>built.</em></h2></div><p className="section-note">Three projects. Three different constraints. The code matters, but the decisions around it matter more.</p></div><div className="project-list">{projects.map(p=><a className={p.featured?"project featured":"project"} key={p.title} href={p.url} target="_blank" rel="noreferrer"><div className="project-number">{p.number}</div><div className="project-main"><p className="project-kicker">{p.kicker}</p><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><span className="project-link">OPEN REPOSITORY <ExternalLink size={13}/></span></div><ProjectVisual project={p}/><ArrowUpRight className="project-arrow"/></a>)}</div></section>

<section id="system" className="machine-section"><div className="machine-copy"><div className="section-index">02</div><p className="eyebrow">Under the hood</p><h2>Take it<br/><em>apart.</em></h2><p>Scroll through the machine. The hardware is a visual metaphor for the way I work: separate the problem, understand every layer, then put the system back together properly.</p><span className="scroll-hint">SCROLL / DISASSEMBLE</span></div><div className="machine-sticky"><MacBook/><div className="machine-label label-a">APPLICATIONS</div><div className="machine-label label-b">BACKEND</div><div className="machine-label label-c">AI / RAG</div><div className="machine-label label-d">DEVOPS</div></div></section>

<section id="about" className="section about"><div className="section-heading compact"><span className="section-index">03</span><div><p className="eyebrow">The engineer</p><h2>More than<br/><em>the stack.</em></h2></div></div><div className="about-grid"><div className="about-statement"><p>I like difficult problems for the right reasons. Systems should be understandable, resilient, and built around the people who have to use them.</p><p>Currently completing a BSc (Hons) in Software Engineering at Lancaster University Leipzig, with an expected graduation in October 2026.</p><a href="mailto:saeedkabak@gmail.com">saeedkabak@gmail.com <ArrowUpRight size={16}/></a></div><div className="skills">{skills.map(([n,name,value])=><div className="skill-row" key={name}><span>{n}</span><strong>{name}</strong><p>{value}</p></div>)}</div></div></section>

<section className="section experience"><div className="section-heading compact"><span className="section-index">04</span><div><p className="eyebrow">Experience</p><h2>Production,<br/><em>not theory.</em></h2></div></div><div className="timeline"><div className="timeline-date">JAN — MAR 2026</div><div><h3>Software Engineer · Technical Lead</h3><p className="company">Helmholtz Centre for Environmental Research (UFZ)</p><p>Led the production delivery of GreenPoint, guiding technical decisions from production readiness through delivery for a mobile field-research application.</p></div></div></section>

<section id="contact" className="section contact"><p className="eyebrow">05 / Get in touch</p><h2>Have a hard<br/><em>problem?</em></h2><a className="contact-email" href="mailto:saeedkabak@gmail.com">saeedkabak@gmail.com <ArrowUpRight/></a><div className="contact-links"><a href="https://github.com/S3eedkabak" target="_blank" rel="noreferrer"><Github size={17}/> GitHub <ExternalLink size={13}/></a><a href="mailto:saeedkabak@gmail.com"><Mail size={17}/> Email</a></div></section>
</main><footer><span>SAEID KABAK © 2026</span><span>BUILT WITH INTENT.</span></footer></div>}