import React,{useMemo,useRef}from"react";import{Canvas,useFrame}from"@react-three/fiber";import{Bounds,Center,Html,useGLTF,useProgress}from"@react-three/drei";import * as THREE from"three";

const MODEL_URL="https://raw.githubusercontent.com/shahdinsalman23/react-macbookpro/main/public/mac.glb";

function Loader(){const{progress}=useProgress();return <Html center><div style={{font:"9px 'DM Mono',monospace",letterSpacing:".14em",color:"#d9ff4f",whiteSpace:"nowrap"}}>LOADING MACHINE {Math.round(progress)}%</div></Html>}

function Model({progress}){const{scene}=useGLTF(MODEL_URL);const root=useRef();const parts=useMemo(()=>{const clone=scene.clone(true);const list=[];clone.traverse(o=>{if(o.isMesh)list.push({o,base:o.position.clone(),rotation:o.rotation.clone(),name:(o.name||"").toLowerCase(),index:list.length})});return{clone,list}},[scene]);const smooth=useRef(0);useFrame((_,delta)=>{const p=THREE.MathUtils.damp(smooth.current,THREE.MathUtils.clamp(progress,0,1),8,delta);smooth.current=p;parts.list.forEach(part=>{const{ o,base,rotation,name,index}=part;const isScreen=name.includes("screen");if(isScreen){o.position.copy(base);o.rotation.set(rotation.x+THREE.MathUtils.degToRad(90)*THREE.MathUtils.smoothstep(p,.05,.7),rotation.y,rotation.z);return}const seed=index*1.6180339887;const direction=new THREE.Vector3(Math.sin(seed*1.7),Math.cos(seed*.9)*.55,Math.cos(seed*1.31));direction.normalize();const distance=.42*THREE.MathUtils.smoothstep(p,.18,.82);o.position.copy(base).addScaledVector(direction,distance);o.rotation.set(rotation.x+Math.sin(seed)*p*.025,rotation.y+Math.cos(seed)*p*.025,rotation.z+Math.sin(seed*1.4)*p*.02)});if(root.current)root.current.rotation.set(THREE.MathUtils.degToRad(3),THREE.MathUtils.degToRad(-8),THREE.MathUtils.degToRad(1))});return <group ref={root}><primitive object={parts.clone} scale={.82}/></group>}

useGLTF.preload(MODEL_URL);

export default function MacBookScene({progress}){return <Canvas className="mac-canvas" camera={{fov:35,position:[0,0,10]}} dpr={[1,1.5]} gl={{antialias:true,alpha:true}}><ambientLight intensity={1.7}/><hemisphereLight intensity={1.1}/><directionalLight position={[5,7,9]} intensity={3}/><directionalLight position={[-5,3,5]} intensity={1.5}/><pointLight position={[0,4,5]} intensity={1.1} color="#d9ff4f"/><Bounds fit margin={1.25}><React.Suspense fallback={<Loader/>}><Center><Model progress={progress}/></Center></React.Suspense></Bounds></Canvas>}